// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5kcnt0aBwfpPIczFbU8_lBmveCFOWTSM',
    appId: '1:487639332494:web:ceea8fe2bd24d362a03bdf',
    messagingSenderId: '487639332494',
    projectId: 'grup51-appjam',
    authDomain: 'grup51-appjam.firebaseapp.com',
    storageBucket: 'grup51-appjam.appspot.com',
    measurementId: 'G-Y9C9ZKGZGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3TZ0_3FJAfr_GqBQBlf8-WNWGBKvn2E',
    appId: '1:487639332494:android:cfe00ce4a90eabeba03bdf',
    messagingSenderId: '487639332494',
    projectId: 'grup51-appjam',
    storageBucket: 'grup51-appjam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE_0eWWryY0ogVtncWaQbIa5-brzIiCIU',
    appId: '1:487639332494:ios:179149a64f339b33a03bdf',
    messagingSenderId: '487639332494',
    projectId: 'grup51-appjam',
    storageBucket: 'grup51-appjam.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE_0eWWryY0ogVtncWaQbIa5-brzIiCIU',
    appId: '1:487639332494:ios:179149a64f339b33a03bdf',
    messagingSenderId: '487639332494',
    projectId: 'grup51-appjam',
    storageBucket: 'grup51-appjam.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5kcnt0aBwfpPIczFbU8_lBmveCFOWTSM',
    appId: '1:487639332494:web:99998db344fd1599a03bdf',
    messagingSenderId: '487639332494',
    projectId: 'grup51-appjam',
    authDomain: 'grup51-appjam.firebaseapp.com',
    storageBucket: 'grup51-appjam.appspot.com',
    measurementId: 'G-Y3EB6159Q2',
  );
}
